services:
  - type: web
    name: hamster-tap
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: ADMIN_ID
        value: 1254600026
      - key: DB_POOL_MAX
        value: 20
      - key: PYTHON_VERSION
        value: 3.11.0
